#!/usr/bin/env python3
"""
catalog.py  --  generate specs/CATALOG.md from the specs (no Blender needed)
============================================================================
Self-documentation: walks every spec and writes a readable summary table +
per-level breakdown. Run it after adding or editing a spec; commit the
updated CATALOG.md alongside. This keeps the repo self-describing as the
level set grows.

    python catalog.py            # writes specs/CATALOG.md
    python catalog.py --check    # exit 1 if CATALOG.md is stale (for CI)
"""

import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from spec_loader import load_spec  # noqa: E402


def _entries(spec):
    """Count exterior ground-level entry openings (doors/garages/breach)."""
    n = 0
    for w in spec.ext_walls:
        if w.story == (-1 if spec.has_basement else 0) or w.story == 0:
            for o in w.openings:
                if o.kind in ("door", "garage", "breach"):
                    n += 1
    return n


def summarize(path):
    spec = load_spec(path)
    breach = sum(1 for w in spec.ext_walls for o in w.openings if o.kind == "breach")
    breach += sum(1 for p in spec.partitions for o in p.openings if o.kind == "breach")
    tactical = None
    try:
        from tactical import analyze
        _, _, sc = analyze(spec)
        if sc.get("tactical"):
            tactical = sc
    except Exception:
        pass
    return {
        "file": os.path.basename(path),
        "name": spec.name,
        "footprint": f"{spec.footprint_x:g}x{spec.footprint_y:g}m",
        "stories": spec.n_stories + (1 if spec.has_basement else 0),
        "basement": "yes" if spec.has_basement else "no",
        "entries": _entries(spec),
        "stairs": len(spec.stairs),
        "slab_holes": len(spec.slab_holes),
        "volumes": len(spec.volumes),
        "breach_points": breach,
        "assets": len(spec.assets),
        "placements": len(spec.placements),
        "rooms": len(spec.rooms),
        "markers": len(spec.markers),
        "tactical": tactical,
        "spec": spec,
    }


def render(rows):
    lines = []
    lines.append("# Deli Counter — level catalog\n")
    lines.append("_Auto-generated by `catalog.py`. Do not edit by hand — "
                 "run `python catalog.py` after changing specs._\n")
    lines.append("| Level | File | Footprint | Floors | Entries | Stairs | "
                 "Breach pts | Volumes | Kitbash |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        kb = f"{r['placements']}x from {r['assets']}" if r["placements"] else "—"
        lines.append(f"| {r['name']} | `{r['file']}` | {r['footprint']} | "
                     f"{r['stories']} | {r['entries']} | {r['stairs']} | "
                     f"{r['breach_points']} | {r['volumes']} | {kb} |")
    lines.append("")
    for r in rows:
        s = r["spec"]
        lines.append(f"## {r['name']}  (`{r['file']}`)\n")
        lines.append(f"- Footprint: {r['footprint']}, story height "
                     f"{s.story_height:g}m, {r['stories']} floor(s)"
                     f"{' incl. basement' if s.has_basement else ''}")
        lines.append(f"- Collision mode: {s.collision}")
        lines.append(f"- Exterior walls defined: {len(s.ext_walls)}; "
                     f"interior partitions: {len(s.partitions)}")
        if s.stairs:
            lines.append(f"- Stairwells: {len(s.stairs)} "
                         f"({', '.join(st.style for st in s.stairs)})")
        if r["breach_points"]:
            lines.append(f"- Breachable points: {r['breach_points']} "
                         f"(removable `*_BREACHPANEL` on import)")
        if s.volumes:
            names = ", ".join(v.name for v in s.volumes)
            lines.append(f"- Volumes: {names}")
        if s.assets:
            alist = ", ".join(f"{a.id} ({a.fmt})" for a in s.assets)
            lines.append(f"- Kitbash assets: {alist}")
            lines.append(f"- Placements: {len(s.placements)} instance(s)")
        if r.get("tactical"):
            t = r["tactical"]
            lines.append(f"- **Tactical**: {t['rooms']} rooms, "
                         f"{t['attacker_entries']} entries, "
                         f"{t['objective_rooms']} objective room(s), "
                         f"{t['breach_points']} breach pts, "
                         f"{t['markers']} markers")
            if s.rooms:
                rnames = ", ".join(f"{rm.id}" + (" (obj)" if (rm.objective or rm.role=="objective_room") else "")
                                   for rm in s.rooms)
                lines.append(f"- Rooms: {rnames}")
        lines.append("")
    return "\n".join(lines)


def main():
    specs = sorted(glob.glob(os.path.join(HERE, "specs", "*.json")))
    rows = [summarize(p) for p in specs]
    content = render(rows)
    out = os.path.join(HERE, "specs", "CATALOG.md")

    if "--check" in sys.argv:
        existing = ""
        if os.path.exists(out):
            with open(out, encoding="utf-8") as f:
                existing = f.read()
        if existing.strip() != content.strip():
            print("CATALOG.md is stale. Run: python catalog.py")
            sys.exit(1)
        print("CATALOG.md up to date.")
        return

    with open(out, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {out} ({len(rows)} levels)")


if __name__ == "__main__":
    main()
